node:
  id: my-node
  token: your-node-token

server:
  address: http://localhost:8080
  heartbeatInterval: 30  # seconds

network:
  enableUPnP: true
  enableNATPMP: true
  stunServers:
    - stun.l.google.com:19302
    - stun.stunprotocol.org:3478
  turnServers:
    - address: turn.example.com:3478
      username: username
      password: password

security:
  enableTLS: true
  certFile: cert.pem
  keyFile: key.pem
  caFile: ca.pem

logging:
  level: info
  file: p3-client.log

# 预配置的应用列表
apps:
  - name: rdp
    protocol: tcp
    srcPort: 13389
    peerNode: remote-node
    dstPort: 3389
    dstHost: localhost
    description: 远程桌面连接
    autoStart: true

  - name: ssh
    protocol: tcp
    srcPort: 12222
    peerNode: remote-node
    dstPort: 22
    dstHost: localhost
    description: SSH 连接
    autoStart: false
