version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "p3"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "p3_secret_key_change_this_in_production"
  accessExpireTime: 1
  refreshExpireTime: 168
  issuer: "p3-server"

security:
  enableRateLimit: true
  enableCSRF: true
  enableTLS: false
  certFile: "cert.pem"
  keyFile: "key.pem"
  allowedOrigins:
    - "http://localhost"
    - "http://localhost:8080"
    - "http://localhost:3000"

p2p:
  udpPort1: 27182
  udpPort2: 27183
  tcpPort: 27184

relay:
  maxBandwidth: 10
  maxClients: 100

log:
  level: "info"
  output: "stdout"
  file: "p3-server.log"

turn:
  address: "0.0.0.0:3478"
  realm: "p3.example.com"
  authSecret: "p3_turn_secret_change_this_in_production"
